POST http://localhost:5000/api/reportIncident HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "event": "fire",
    "coordinates": [
        40.741895,
        -73.989308
    ]
}